export const bannerConstants = {
    GET_BANNERS_REQUEST: "GET_BANNERS_REQUEST",
    GET_BANNERS_SUCCESS: "GET_BANNERS_SUCCESS",
    GET_BANNERS_FAILURE: "GET_BANNERS_FAILURE",
}
export const brandConstants = {
    GET_BRAND_REQUEST: "GET_BRAND_REQUEST",
    GET_BRAND_SUCCESS: "GET_BRAND_SUCCESS",
    GET_BRAND_FAILURE: "GET_BRAND_FAILURE",

    GET_DINE_BRAND_REQUEST: "GET_DINE_BRAND_REQUEST",
    GET_DINE_BRAND_SUCCESS: "GET_DINE_BRAND_SUCCESS",
    GET_DINE_BRAND_FAILURE: "GET_DINE_BRAND_FAILURE"
}

export const eventConstants = {
    GET_EVENT_REQUEST: "GET_EVENT_REQUEST",
    GET_EVENT_SUCCESS: "GET_EVENT_SUCCESS",
    GET_EVENT_FAILURE: "GET_EVENT_FAILURE",
}

export const galleryConstants = {
    GET_GALLERY_IMG_REQUEST: "GET_GALLERY_IMG_REQUEST",
    GET_GALLERY_IMG_SUCCESS: "GET_GALLERY_IMG_SUCCESS",
    GET_GALLERY_IMG_FAILURE: "GET_GALLERY_IMG_FAILURE",
}

export const offerConstants = {
    GET_OFFER_REQUEST: "GET_OFFER_REQUEST",
    GET_OFFER_SUCCESS: "GET_OFFER_SUCCESS",
    GET_OFFER_FAILURE: "GET_OFFER_FAILURE",
}

export const careerConstants = {
    ADD_CAREER_REQUEST: "ADD_CAREER_REQUEST",
    ADD_CAREER_SUCCESS: "ADD_CAREER_SUCCESS",
    ADD_CAREER_FAILURE: "ADD_CAREER_FAILURE",
}

export const enquiryConstants = {
    ADD_ENQUIRY_REQUEST: "ADD_ENQUIRY_REQUEST",
    ADD_ENQUIRY_SUCCESS: "ADD_ENQUIRY_SUCCESS",
    ADD_ENQUIRY_FAILURE: "ADD_ENQUIRY_FAILURE",
}

export const vacancyConstants = {
    GET_VACANCY_REQUEST: "GET_VACANCY_REQUEST",
    GET_VACANCY_SUCCESS: "GET_VACANCY_SUCCESS",
    GET_VACANCY_FAILURE: "GET_VACANCY_FAILURE",
}

export const notificationConstants = {
    CREATE_NOTIFICATION_REQUEST: "CREATE_NOTIFICATION_REQUEST",
    CREATE_NOTIFICATION_SUCCESS: "CREATE_NOTIFICATION_SUCCESS",
    CREATE_NOTIFICATION_FAILURE: "CREATE_NOTIFICATION_FAILURE"
}